FORMAT: 1A
HOST: https://dictionary.iachieved.it/

# Dictionary

## Dictionary [/dictionary]

### Create a New Dictionary [POST]

Create a new dictionary.

+ Request (application/json)

        {}

+ Response 201 (application/json)

    + Body

        {
            "id":"dictionary-id"
        }
            
### Delete a Dictionary [DELETE]

Delete a dictionary.

+ Request (application/json)     

+ Response 200 (application/json)

+ Response 404 (application/json)
            
## Dictionary [/dictionary/{id}]
            
    + Parameters
        + id
        
### Create or Modify a Key-Value Pair [POST]

+ Request (application/json)


    + Body

        {
          "key":"KEY"
          "value":"VALUE"
        }
        
+ Response 201 (applicationjson)

### Get a Value [GET]

Given a key, returns a value.

+ Request (application/json)

        {
            "key":"KEY"
        }
        
+ Response 200 (application/json)

        {
            "value":"value"
        }

+ Response 404 (application/json)

### Get all Keys [GET]

Returns all keys in the dictionary.

+ Request (application/json)

+ Response 200 (application/json)

    {
        "count": n,
        "keys": [
            "key1",
            "key2",
            ...,
            "keyn"
        ]
    }
    
+ Response 404 (application/json)

### Get all Keys and Values [GET]

Returns all keys and values in the dictionary.

+ Request (application/json)

+ Response 200 (application/json)

+ Response 404 (application/json)

### Delete a Key-Value Pair [DELETE]

+ Request (application/json)